@baseUrl = http://localhost:3000/api

### Create User ลำดับที่ 1
POST {{baseUrl}}/users
Content-Type: application/json

{
  "username": "carttester",
  "email": "carttester2@test.com",
  "password": "password123",
  "fullName": "Cart Tester"
}

### Login User ลำดับที่ 2
POST {{baseUrl}}/users/login
Content-Type: application/json

{
  "email": "carttester2@test.com",
  "password": "password123"
}

### Create Cart ลำดับที่ 3
POST {{baseUrl}}/cart
Content-Type: application/json
Cookie: accessToken=PUT_ACCESS_TOKEN_HERE

{
  "user_id": "6a1e8437ddf47f9d36c7aef8",
  "total_amount": 599,
  "status": "pending",
  "cart_item": [
    {
      "book_id": "685abc123456789012345679",
      "book_name": "Atomic Habits Cart Test",
      "author": "James Clear Cart Test",
      "quantity": 1,
      "price": 599,
      "img_link": "https://example.com/book.jpg"
    }
  ]
}

### Get Cart By User ID ลำดับที่ 4
GET {{baseUrl}}/cart/6a1e84d8ddf47f9d36c7aef9
Cookie: accessToken=PUT_ACCESS_TOKEN_HERE

### Update Cart ลำดับที่ 5
PATCH {{baseUrl}}/cart/6a1e84d8ddf47f9d36c7aef9
Content-Type: application/json
Cookie: accessToken=PUT_ACCESS_TOKEN_HERE

{
  "total_amount": 1198,
  "cart_item": [
    {
      "book_id": "685abc123456789012345679",
      "book_name": "Atomic Habits Cart Test",
      "author": "James Clear Cart Test",
      "quantity": 2,
      "price": 599,
      "img_link": "https://example.com/book.jpg"
    }
  ]
}

### Delete Cart ลำดับที่ 6
DELETE {{baseUrl}}/cart/6a1e84d8ddf47f9d36c7aef9
Cookie: accessToken=PUT_ACCESS_TOKEN_HERE